AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  devfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::845068533700:role/MyLambdaRole'
      Events:
        DEVAPI:
          Type: Api
          Properties:
            Path: /DEV
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-2
